[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino

lib_deps =
    madhephaestus/ESP32Servo@^3.0.5

monitor_speed = 115200
; Lower speed is much more reliable with this CP210x cable/robot wiring.
upload_speed = 115200

build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D ARDUINO_USB_CDC_ON_BOOT=0
